/**
 * Do not edit directly, this file was auto-generated.
 */

export const PrimitivesPurple50 = "#FAF7FF";
export const PrimitivesPurple100 = "#F0E9FB"; // Purple Light — subtle bg
export const PrimitivesPurple600 = "#7C35EB"; // Hover / dark mode
export const PrimitivesPurple700 = "#6D28D9"; // Purple Heart — main brand
export const PrimitivesPurple800 = "#4E22B0";
export const PrimitivesPurple900 = "#3B1A8A"; // Purple darkest
export const PrimitivesNeutral0 = "#FFFFFF"; // Pure White
export const PrimitivesNeutral50 = "#FCFCFC"; // Alabaster
export const PrimitivesNeutral100 = "#F7F8FA"; // Shatlevka — page bg
export const PrimitivesNeutral200 = "#EBEBEB"; // Warm Gray — borders
export const PrimitivesNeutral400 = "#AEAEAE"; // Soft Gray — disabled
export const PrimitivesNeutral600 = "#717182"; // Storm Gray — secondary text
export const PrimitivesNeutral800 = "#1E1E1E"; // PopUp Gray
export const PrimitivesNeutral950 = "#0A0A0A"; // Cod Gray — primary text
export const PrimitivesGreen100 = "#DCFCE7"; // Persian Light — success bg
export const PrimitivesGreen700 = "#009689"; // Persian Green — success
export const PrimitivesOrange100 = "#FFEDD4"; // California Light — warning bg
export const PrimitivesOrange500 = "#FE9A00"; // California — warning
export const PrimitivesRed100 = "#FFDDDB"; // Vermilion Light — error bg
export const PrimitivesRed600 = "#F54900"; // Vermilion — error
export const SemanticColorBrandDefault = "#6D28D9";
export const SemanticColorBrandHover = "#7C35EB";
export const SemanticColorBrandSubtle = "#F0E9FB";
export const SemanticColorBgPage = "#F7F8FA";
export const SemanticColorBgSurface = "#FFFFFF";
export const SemanticColorBgOverlay = "#1E1E1E";
export const SemanticColorTextPrimary = "#0A0A0A";
export const SemanticColorTextSecondary = "#717182";
export const SemanticColorTextDisabled = "#AEAEAE";
export const SemanticColorTextInverse = "#FCFCFC";
export const SemanticColorTextBrand = "#6D28D9";
export const SemanticColorBorderDefault = "#EBEBEB";
export const SemanticColorBorderBrand = "#6D28D9";
export const SemanticColorBorderFocus = "#7C35EB";
export const SemanticColorStatusSuccess = "#009689";
export const SemanticColorStatusSuccessSubtle = "#DCFCE7";
export const SemanticColorStatusWarning = "#FE9A00";
export const SemanticColorStatusWarningSubtle = "#FFEDD4";
export const SemanticColorStatusError = "#F54900";
export const SemanticColorStatusErrorSubtle = "#FFDDDB";
export const ComponentButtonPrimaryBg = "#6D28D9";
export const ComponentButtonPrimaryBgHover = "#7C35EB";
export const ComponentButtonPrimaryText = "#FCFCFC";
export const ComponentButtonSecondaryBg = "#FFFFFF";
export const ComponentButtonSecondaryBgHover = "#F0E9FB";
export const ComponentButtonSecondaryText = "#6D28D9";
export const ComponentButtonSecondaryBorder = "#EBEBEB";
export const ComponentButtonSecondaryBorderHover = "#6D28D9";
export const ComponentButtonGhostBg = "#F7F8FA";
export const ComponentButtonGhostBgHover = "#F0E9FB";
export const ComponentButtonGhostText = "#6D28D9";
export const ComponentButtonDisabledText = "#AEAEAE";
export const ComponentButtonDisabledBorder = "#EBEBEB";
export const Spacing1 = "4";
export const Spacing2 = "8";
export const Spacing3 = "12";
export const Spacing4 = "16";
export const Spacing5 = "20";
export const Spacing6 = "24";
export const Spacing8 = "32";
export const Spacing10 = "40";
export const Spacing12 = "48";
export const RadiusSm = "4";
export const RadiusMd = "8";
export const RadiusLg = "12";
export const RadiusXl = "16";
export const RadiusFull = "999";
